android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.download.timeout=300000
android.suppressUnsupportedCompileSdk=34
#kotlin.version=1.8.20
##org.gradle.distribution.version=8.2
##kotlin.version=1.8.10
org.gradle.jvmargs=-Xmx2g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
#org.gradle.jvmargs=-Xmx512m
#org.gradle.jvmargs=-Xmx4096m
#org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
#org.gradle.jvmargs=-Xmx1024m
#org.gradle.jvmargs=-Xmx2048m
#org.gradle.jvmargs=-Xmx1536m
#org.gradle.jvmargs=-Xmx3g
org.gradle.logging.level=info
#org.gradle.jvmargs=-Xmx2048m -Xms1024m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
#org.gradle.jvmargs=-Xmx512m -XX:MaxMetaspaceSize=256m
